# -*- coding: utf-8 -*-
"""loops.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sr2dNui8uN1W7sgT2eeAmhZpUAC20Z0u

The Input statement

-Helps get info from the keyboard
"""

# Takes data from the keyboard
# Return result is always a string
#name = input()
number = int(input())

# Converting to int
#number = int('5')

# converting to str

#str_number = str(number)

print('This is a number' , number)

"""Data Type Conversion"""

# To str
#str()

# To int
#int()

# To List
#list()

"""While loop and Examples

While loops execute until a true condition is false or a false condition is true
"""

spam = 0

if spam < 5:
  print('Hello World')
  spam = spam + 1


while spam < 5:
  print('Hello World')
  spam = spam + 1

"""Break and Continue Statements

Break statements allow us to exit our loop early or before the condition is met


"""

# Example of a break statement
spam = 0

while spam < 5:
  print('Hello World')

  print('The value of spam is', spam)

  spam = spam + 1

  if spam == 3:
    break

# Example of a continue statement

while True:

  print('Who are you?: ')
  user_name = input()

  if user_name != 'Mykel':
    continue
  print('Welcome', user_name)
  break

"""The range data type

prints values from a starting index to an ending index exclusive of the ending index
"""

range(1,5)
# 1, 2, 3, 4

range(5)

# 0, 1, 2, 3, 4

range(8,9)

# 8

range(0,5,1)

# 0, 1, 2, 3, 4

range(0,5,2)

# 0, 2, 4

"""For loops

Runs a number of times based on the range or iterable condition provided
"""

for number in range(0,5,2):
  print(number)

names_of_students = ['mykel', 'sam', 'jon']

for name_of_student in names_of_students:
  print(name_of_student)

for i in range(5):
  print('Hello World')

for _ in range(5):
  print('Hello World')