# -*- coding: utf-8 -*-
"""python_basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tna8PMvarzXwKkh-lAREzPfm5G8QvHfP
"""

## Examples of variables

name = "Mykel"

car_model = "Accord"

## Variable year is storing the value of year

year = "2022" # String

## Showed different types of variables

country = "united states" # String 

num_of_students = 5 # Int 

num_of_teachers = 10 # int

# We showed how to store values in a variable

num_of_teachers_students = num_of_students + num_of_teachers

# print variables
print(num_of_teachers_students)

print(num_of_teachers)

# We can add variables of the same type

year_country = country + year

print(year_country)

# Other types of variables

price_of_soda = 1.99 # float or double
price_of_water = 2 # int
price_of_cookies = 2.00 # float

print(price_of_water == price_of_cookies) # Value is the same across datatypes
print(type(price_of_water) == type(price_of_cookies)) # Types are different

print(type(price_of_cookies))

# list datatype
student_names = ["Joe" ,"Sam",  "Mykel"]

print(student_names)

# Declared an example of a list data type

brands_of_laptops = ["Apple", "Microsoft", "HP"]

print(brands_of_laptops)

# We showed that list variables can contain different datatype of variables and also variables

alpha_numeric = ["A" ,"B" ,"C", 1, 2, 3, 4.0, brands_of_laptops]

print(alpha_numeric)

# Operators

"+", "-", "*", "/", "%", "^"

# Addition Examples

# Example of int
number_of_cars = 6
number_of_trucks = 10

# Uncomment to display value
#print(number_of_cars + number_of_trucks)

# Example of strings
first_name = "Mykel"
last_name = "Doe"

# Uncomment to display value
#print(first_name + " " + last_name)

# Example of floats
price_of_car = 19999.23
price_of_registration = 200.45

# Uncomment to display value
#total_cost = price_of_car + price_of_registration 

#print(total_cost)

# Example of list
names_students = ["mykel", "sam", "joe"]
names_of_teachers = ["bob", "john", "alice"]

all_students_teachers = names_of_teachers + names_students

print(all_students_teachers)



# Multiplication Examples

# Example of int
number_of_cars = 6
number_of_trucks = 10

# Uncomment to display value
#print(number_of_cars * number_of_trucks)

# Example of strings
first_name = "Mykel"
last_name = "Doe"
value = 5 # Value is an int

# Uncomment to display value
#print(first_name * value)

# Example of floats
price_of_car = 19999.23
price_of_registration = 200.45

total_cost = price_of_car * price_of_registration 

# Uncomment to display value
#print(total_cost)

# Example of list
names_students = ["mykel", "sam", "joe"]
names_of_teachers = ["bob", "john", "alice"]
value = 5

all_students_teachers = names_of_teachers * value

print(all_students_teachers)

